import argparse
import re

import matplotlib.pyplot as plt
import pandas as pd

from analysis_utils import ensure_directories, load_negative_reviews
from config import OUTPUT_DIR

DEFAULT_THRESHOLDS = [10, 20, 30, 40, 50]

SOFT_KEYWORDS = [
    "ai",
    "artificial intelligence",
    "generative",
    "algorithm",
    "gpt",
    "llm",
    "prompt",
    "stable diffusion",
    "midjourney",
    "chatgpt",
    "suno",
    "udio",
    "machine learning",
    "ethical",
    "ethics",
    "unethical",
    "plagiarism",
    "stolen",
    "theft",
    "steal",
    "copyright",
    "scrape",
    "scraping",
    "training data",
    "consent",
    "lawsuit",
    "infringement",
    "soulless",
    "slop",
    "ai slop",
    "generic",
    "bland",
    "low effort",
    "lazy",
    "synthetic",
    "artificial",
    "uncanny",
    "weird fingers",
    "garbage",
    "trash",
    "cheap",
    "artist",
    "voice actor",
    "voiceover",
    "human",
    "real person",
    "handmade",
    "talent",
    "soul",
    "passion",
    "creativity",
]

STRICT_KEYWORDS = [
    "ai ",
    "artificial intelligence",
    "generative",
    "chatgpt",
    "midjourney",
    "stable diffusion",
    "suno",
    "udio",
    "llm",
    "machine learning",
    "ai-generated",
    "ai generated",
    "generated by ai",
]

LABEL_MAP = {
    "Group 1 (Native AI)": "Newly AI-lab.",
    "Group 2 (AI Added - Recent)": "Retro. AI-lab.",
    "Group 2 (AI Added - Historic)": "Retro. AI-lab. (hist.)",
    "Group 3 (Control / No AI)": "No AI label",
}

plt.rcParams.update(
    {
        "font.size": 24,
        "axes.titlesize": 32,
        "axes.labelsize": 30,
        "xtick.labelsize": 24,
        "ytick.labelsize": 24,
        "legend.fontsize": 22,
    }
)


def parse_thresholds(raw: str):
    values = []
    for item in raw.split(","):
        item = item.strip()
        if not item:
            continue
        values.append(int(item))
    values = sorted(set(v for v in values if v > 0))
    return values or DEFAULT_THRESHOLDS


def get_pattern(word_list):
    escaped = [rf"\b{re.escape(word.lower())}\b" for word in word_list]
    return "|".join(escaped)


def wilson_interval(k, n, z=1.96):
    if n == 0:
        return 0.0, 0.0

    phat = k / n
    denom = 1.0 + (z**2 / n)
    center = (phat + (z**2 / (2 * n))) / denom
    margin = (z / denom) * ((phat * (1 - phat) / n + z**2 / (4 * n**2)) ** 0.5)
    low = max(0.0, center - margin)
    high = min(1.0, center + margin)
    return low, high


def load_negative_with_labels():
    df = load_negative_reviews()
    if df.empty:
        raise RuntimeError("Keine negativen Reviews gefunden.")

    df["appid"] = pd.to_numeric(df["appid"], errors="coerce")
    df = df.dropna(subset=["appid"]).copy()
    df["appid"] = df["appid"].astype(int)

    text = df["review_text"].astype(str).fillna("").str.lower()
    soft_pattern = get_pattern(SOFT_KEYWORDS)
    strict_pattern = get_pattern(STRICT_KEYWORDS)
    df["is_ai_criticism"] = text.str.contains(soft_pattern, regex=True, na=False)
    df["strict_ai_criticism"] = text.str.contains(strict_pattern, regex=True, na=False)
    return df


def compute_group_metrics(df, group_name, threshold):
    group_df = df[df["BA_Group"] == group_name].copy()
    total_games = group_df["appid"].nunique()
    total_reviews = len(group_df)

    app_review_counts = group_df.groupby("appid").size()
    eligible_appids = app_review_counts[app_review_counts >= threshold].index
    filtered = group_df[group_df["appid"].isin(eligible_appids)].copy()

    n_games = filtered["appid"].nunique()
    n_reviews = len(filtered)
    strict_hits = int(filtered["strict_ai_criticism"].sum())
    soft_hits = int(filtered["is_ai_criticism"].sum())

    strict_pct = (strict_hits / n_reviews) * 100 if n_reviews else 0.0
    soft_pct = (soft_hits / n_reviews) * 100 if n_reviews else 0.0

    strict_ci_low, strict_ci_high = wilson_interval(strict_hits, n_reviews)
    soft_ci_low, soft_ci_high = wilson_interval(soft_hits, n_reviews)

    return {
        "threshold_min_reviews_per_game": threshold,
        "BA_Group": group_name,
        "n_games_total": total_games,
        "n_reviews_total": total_reviews,
        "n_games_kept": n_games,
        "n_reviews_kept": n_reviews,
        "game_coverage_pct": (n_games / total_games * 100) if total_games else 0.0,
        "review_coverage_pct": (n_reviews / total_reviews * 100) if total_reviews else 0.0,
        "strict_hits": strict_hits,
        "soft_hits": soft_hits,
        "strict_pct": strict_pct,
        "soft_pct": soft_pct,
        "strict_ci95_low_pct": strict_ci_low * 100,
        "strict_ci95_high_pct": strict_ci_high * 100,
        "soft_ci95_low_pct": soft_ci_low * 100,
        "soft_ci95_high_pct": soft_ci_high * 100,
    }


def plot_metric(df, metric_col, title, ylabel, output_file):
    fig = plt.figure(figsize=(14, 10))
    for group_name in sorted(df["BA_Group"].unique()):
        group_df = df[df["BA_Group"] == group_name].sort_values("threshold_min_reviews_per_game")
        plt.plot(
            group_df["threshold_min_reviews_per_game"],
            group_df[metric_col],
            marker="o",
            markersize=11,
            linewidth=3.4,
            label=LABEL_MAP.get(group_name, group_name),
        )

    # The paper caption already names the plot; keep the image area for readable axes.
    plt.xlabel("Minimum reviews per game")
    plt.ylabel(ylabel)
    plt.grid(alpha=0.3)
    plt.legend(
        loc="upper center",
        bbox_to_anchor=(0.5, -0.16),
        ncol=2,
        framealpha=0.95,
        columnspacing=1.2,
        handlelength=2.0,
    )
    plt.tight_layout(rect=[0, 0.08, 1, 1], pad=1.0)
    fig.savefig(output_file, dpi=320)
    plt.close(fig)


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Sensitivitaetsanalyse fuer unterschiedliche Mindestanzahl Reviews pro Spiel "
            "(z. B. 10/20/30), basierend auf Broad- und Focused-KI-Kritik."
        )
    )
    parser.add_argument(
        "--thresholds",
        type=str,
        default="10,20,30,40,50",
        help="Komma-separierte Liste, z. B. 10,20,30",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    thresholds = parse_thresholds(args.thresholds)
    ensure_directories()

    df = load_negative_with_labels()
    groups = sorted(df["BA_Group"].dropna().unique())

    rows = []
    for threshold in thresholds:
        for group_name in groups:
            rows.append(compute_group_metrics(df, group_name, threshold))

        # overall-zeile
        all_row = compute_group_metrics(df.assign(BA_Group="ALL_GROUPS"), "ALL_GROUPS", threshold)
        rows.append(all_row)

    result = pd.DataFrame(rows).sort_values(
        by=["threshold_min_reviews_per_game", "BA_Group"]
    )

    out_csv = OUTPUT_DIR / "threshold_sensitivity_by_group.csv"
    result.to_csv(out_csv, index=False)

    plot_df = result[result["BA_Group"] != "ALL_GROUPS"].copy()
    plot_metric(
        plot_df,
        metric_col="strict_pct",
        title="Threshold Sensitivity - Focused Keyword Set",
        ylabel="Focused keyword rate [%]",
        output_file=OUTPUT_DIR / "threshold_sensitivity_strict.png",
    )
    plot_metric(
        plot_df,
        metric_col="soft_pct",
        title="Threshold Sensitivity - Broad Keyword Set",
        ylabel="Broad keyword rate [%]",
        output_file=OUTPUT_DIR / "threshold_sensitivity_soft.png",
    )
    plot_metric(
        plot_df,
        metric_col="review_coverage_pct",
        title="Threshold Sensitivity - Review Coverage",
        ylabel="Review Coverage [%]",
        output_file=OUTPUT_DIR / "threshold_sensitivity_coverage.png",
    )

    print(f"FERTIG: {out_csv}")
    print(f"Thresholds: {thresholds}")


if __name__ == "__main__":
    main()
