import argparse
import re

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from analysis_utils import ensure_directories, load_negative_reviews
from config import OUTPUT_DIR

DEFAULT_THRESHOLDS = [10, 20, 30, 40, 50]

SOFT_KEYWORDS = [
    "ai",
    "artificial intelligence",
    "generative",
    "algorithm",
    "gpt",
    "llm",
    "prompt",
    "stable diffusion",
    "midjourney",
    "chatgpt",
    "suno",
    "udio",
    "machine learning",
    "ethical",
    "ethics",
    "unethical",
    "plagiarism",
    "stolen",
    "theft",
    "steal",
    "copyright",
    "scrape",
    "scraping",
    "training data",
    "consent",
    "lawsuit",
    "infringement",
    "soulless",
    "slop",
    "ai slop",
    "generic",
    "bland",
    "low effort",
    "lazy",
    "synthetic",
    "artificial",
    "uncanny",
    "weird fingers",
    "garbage",
    "trash",
    "cheap",
    "artist",
    "voice actor",
    "voiceover",
    "human",
    "real person",
    "handmade",
    "talent",
    "soul",
    "passion",
    "creativity",
]

STRICT_KEYWORDS = [
    "ai ",
    "artificial intelligence",
    "generative",
    "chatgpt",
    "midjourney",
    "stable diffusion",
    "suno",
    "udio",
    "llm",
    "machine learning",
    "ai-generated",
    "ai generated",
    "generated by ai",
]

LABEL_MAP = {
    "Group 1 (Native AI)": "Newly AI-lab.",
    "Group 2 (AI Added - Recent)": "Retro. AI-lab.",
    "Group 2 (AI Added - Historic)": "Retro. AI-lab. (hist.)",
    "Group 3 (Control / No AI)": "No AI label",
}

plt.rcParams.update(
    {
        "font.size": 24,
        "axes.titlesize": 32,
        "axes.labelsize": 30,
        "xtick.labelsize": 24,
        "ytick.labelsize": 24,
        "legend.fontsize": 22,
    }
)


def parse_thresholds(raw: str):
    values = []
    for item in raw.split(","):
        item = item.strip()
        if not item:
            continue
        values.append(int(item))
    values = sorted(set(v for v in values if v > 0))
    return values or DEFAULT_THRESHOLDS


def get_pattern(word_list):
    escaped = [rf"\b{re.escape(word.lower())}\b" for word in word_list]
    return "|".join(escaped)


def load_negative_with_labels():
    df = load_negative_reviews()
    if df.empty:
        raise RuntimeError("Keine negativen Reviews gefunden.")

    df["appid"] = pd.to_numeric(df["appid"], errors="coerce")
    df = df.dropna(subset=["appid"]).copy()
    df["appid"] = df["appid"].astype(int)

    text = df["review_text"].astype(str).fillna("").str.lower()
    df["is_ai_criticism"] = text.str.contains(get_pattern(SOFT_KEYWORDS), regex=True, na=False)
    df["strict_ai_criticism"] = text.str.contains(get_pattern(STRICT_KEYWORDS), regex=True, na=False)
    return df


def bootstrap_cluster_rate(
    game_sizes: np.ndarray,
    game_hits: np.ndarray,
    n_boot: int,
    rng: np.random.Generator,
):
    n_games = len(game_sizes)
    if n_games == 0:
        return np.array([], dtype=float), 0.0

    point_rate = float(game_hits.sum() / game_sizes.sum()) if game_sizes.sum() > 0 else 0.0
    draws = np.empty(n_boot, dtype=float)

    for i in range(n_boot):
        sample_idx = rng.integers(0, n_games, size=n_games)
        sample_n = game_sizes[sample_idx].sum()
        if sample_n <= 0:
            draws[i] = 0.0
            continue
        sample_hits = game_hits[sample_idx].sum()
        draws[i] = sample_hits / sample_n

    return draws, point_rate


def summarize_draws(draws: np.ndarray):
    if draws.size == 0:
        return {
            "boot_mean_pct": np.nan,
            "boot_std_pct": np.nan,
            "boot_ci95_low_pct": np.nan,
            "boot_ci95_high_pct": np.nan,
        }

    return {
        "boot_mean_pct": float(np.mean(draws) * 100),
        "boot_std_pct": float(np.std(draws, ddof=1) * 100),
        "boot_ci95_low_pct": float(np.quantile(draws, 0.025) * 100),
        "boot_ci95_high_pct": float(np.quantile(draws, 0.975) * 100),
    }


def prepare_group_arrays(group_df: pd.DataFrame, metric_col: str):
    grouped = group_df.groupby("appid")
    game_sizes = grouped.size().values.astype(np.int64)
    game_hits = grouped[metric_col].sum().values.astype(np.int64)
    return game_sizes, game_hits


def filter_by_threshold(group_df: pd.DataFrame, threshold: int):
    counts = group_df.groupby("appid").size()
    keep_appids = counts[counts >= threshold].index
    return group_df[group_df["appid"].isin(keep_appids)].copy()


def run_bootstrap(df: pd.DataFrame, thresholds, n_boot: int, seed: int):
    rng = np.random.default_rng(seed)
    groups = sorted(df["BA_Group"].dropna().unique())
    control_name = "Group 3 (Control / No AI)"

    rows = []
    diff_rows = []
    draws_cache = {}

    for threshold in thresholds:
        for group_name in groups:
            subset = filter_by_threshold(df[df["BA_Group"] == group_name], threshold)
            n_games = subset["appid"].nunique()
            n_reviews = len(subset)
            if n_games == 0 or n_reviews == 0:
                continue

            for metric_col in ["strict_ai_criticism", "is_ai_criticism"]:
                game_sizes, game_hits = prepare_group_arrays(subset, metric_col)
                draws, point_rate = bootstrap_cluster_rate(game_sizes, game_hits, n_boot=n_boot, rng=rng)
                summary = summarize_draws(draws)

                metric_name = "strict_pct" if metric_col == "strict_ai_criticism" else "soft_pct"
                rows.append(
                    {
                        "threshold_min_reviews_per_game": threshold,
                        "BA_Group": group_name,
                        "metric": metric_name,
                        "n_games_kept": int(n_games),
                        "n_reviews_kept": int(n_reviews),
                        "point_estimate_pct": point_rate * 100,
                        **summary,
                    }
                )
                draws_cache[(threshold, group_name, metric_name)] = draws

        # diff vs control
        for group_name in groups:
            if group_name == control_name:
                continue
            for metric_name in ["strict_pct", "soft_pct"]:
                a = draws_cache.get((threshold, group_name, metric_name))
                b = draws_cache.get((threshold, control_name, metric_name))
                if a is None or b is None or len(a) == 0 or len(b) == 0:
                    continue

                diff = (a - b) * 100
                diff_rows.append(
                    {
                        "threshold_min_reviews_per_game": threshold,
                        "group_vs_control": f"{group_name} - {control_name}",
                        "metric": metric_name,
                        "diff_point_estimate_pct_points": float(np.mean(diff)),
                        "diff_std_pct_points": float(np.std(diff, ddof=1)),
                        "diff_ci95_low_pct_points": float(np.quantile(diff, 0.025)),
                        "diff_ci95_high_pct_points": float(np.quantile(diff, 0.975)),
                    }
                )

    return pd.DataFrame(rows), pd.DataFrame(diff_rows)


def plot_errorbars(group_df: pd.DataFrame, metric: str, output_file):
    plot_df = group_df[group_df["metric"] == metric].copy()
    if plot_df.empty:
        return

    fig = plt.figure(figsize=(14, 10))
    for group_name in sorted(plot_df["BA_Group"].unique()):
        sub = plot_df[plot_df["BA_Group"] == group_name].sort_values("threshold_min_reviews_per_game")
        x = sub["threshold_min_reviews_per_game"].values
        y = sub["point_estimate_pct"].values
        yerr_low = y - sub["boot_ci95_low_pct"].values
        yerr_high = sub["boot_ci95_high_pct"].values - y
        plt.errorbar(
            x,
            y,
            yerr=[yerr_low, yerr_high],
            marker="o",
            markersize=11,
            linewidth=3.4,
            elinewidth=2.6,
            capsize=6,
            label=LABEL_MAP.get(group_name, group_name),
        )

    ylabel = "Focused keyword rate [%]" if metric == "strict_pct" else "Broad keyword rate [%]"
    plt.xlabel("Minimum reviews per game")
    plt.ylabel(ylabel)
    plt.grid(alpha=0.3)
    plt.legend(
        loc="upper center",
        bbox_to_anchor=(0.5, -0.16),
        ncol=2,
        framealpha=0.95,
        columnspacing=1.2,
        handlelength=2.0,
    )
    plt.tight_layout(rect=[0, 0.08, 1, 1], pad=1.0)
    fig.savefig(output_file, dpi=320)
    plt.close(fig)


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Bestimmt Varianz der Ergebnis-Schaetzer via Cluster-Bootstrap "
            "(Sampling auf Spielebene) fuer Focused/Broad-Metriken."
        )
    )
    parser.add_argument(
        "--thresholds",
        type=str,
        default="10,20,30,40,50",
        help="Komma-separierte Thresholds, z. B. 10,20,30,40,50",
    )
    parser.add_argument(
        "--n-boot",
        type=int,
        default=1000,
        help="Anzahl Bootstrap-Resamples pro Gruppe/Threshold.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random-Seed fuer reproduzierbare Ergebnisse.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    thresholds = parse_thresholds(args.thresholds)
    ensure_directories()

    df = load_negative_with_labels()
    group_metrics, diff_metrics = run_bootstrap(
        df=df,
        thresholds=thresholds,
        n_boot=args.n_boot,
        seed=args.seed,
    )

    group_out = OUTPUT_DIR / "variance_bootstrap_group_metrics.csv"
    diff_out = OUTPUT_DIR / "variance_bootstrap_diff_vs_control.csv"
    group_metrics.to_csv(group_out, index=False)
    diff_metrics.to_csv(diff_out, index=False)

    plot_errorbars(group_metrics, metric="strict_pct", output_file=OUTPUT_DIR / "variance_bootstrap_strict.png")
    plot_errorbars(group_metrics, metric="soft_pct", output_file=OUTPUT_DIR / "variance_bootstrap_soft.png")

    print(f"FERTIG: {group_out}")
    print(f"FERTIG: {diff_out}")
    print(f"Thresholds: {thresholds} | n_boot={args.n_boot} | seed={args.seed}")


if __name__ == "__main__":
    main()
