import argparse
import re
from collections import Counter
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

from analysis_utils import ensure_directories, load_negative_reviews, load_positive_reviews, slugify
from config import OUTPUT_DIR

try:
    from wordcloud import WordCloud

    HAS_WORDCLOUD = True
except Exception:
    HAS_WORDCLOUD = False


# ba keywords soft + strict
KEYWORDS_TECH = [
    "ai",
    "artificial intelligence",
    "generative",
    "algorithm",
    "gpt",
    "llm",
    "prompt",
    "stable diffusion",
    "midjourney",
    "chatgpt",
    "suno",
    "udio",
    "machine learning",
]
KEYWORDS_ETHICS = [
    "ethical",
    "ethics",
    "unethical",
    "plagiarism",
    "stolen",
    "theft",
    "steal",
    "copyright",
    "scrape",
    "scraping",
    "training data",
    "consent",
    "lawsuit",
    "infringement",
]
KEYWORDS_QUALITY = [
    "soulless",
    "slop",
    "ai slop",
    "generic",
    "bland",
    "low effort",
    "lazy",
    "synthetic",
    "artificial",
    "uncanny",
    "weird fingers",
    "garbage",
    "trash",
    "cheap",
]
KEYWORDS_HUMAN = [
    "artist",
    "voice actor",
    "voiceover",
    "human",
    "real person",
    "handmade",
    "talent",
    "soul",
    "passion",
    "creativity",
]
STRICT_KEYWORDS = [
    "ai",
    "artificial intelligence",
    "generative",
    "chatgpt",
    "midjourney",
    "stable diffusion",
    "suno",
    "udio",
    "llm",
    "machine learning",
    "ai-generated",
    "ai generated",
    "generated by ai",
]


def detect_font_path():
    candidates = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf",
        "/usr/share/fonts/truetype/freefont/FreeSans.ttf",
    ]
    for candidate in candidates:
        p = Path(candidate)
        if p.exists():
            return str(p)
    return None


def build_keyword_table():
    rows = []
    for keyword in KEYWORDS_TECH:
        rows.append({"keyword": keyword.strip().lower(), "category": "tech", "source_filter": "soft"})
    for keyword in KEYWORDS_ETHICS:
        rows.append({"keyword": keyword.strip().lower(), "category": "ethics", "source_filter": "soft"})
    for keyword in KEYWORDS_QUALITY:
        rows.append({"keyword": keyword.strip().lower(), "category": "quality", "source_filter": "soft"})
    for keyword in KEYWORDS_HUMAN:
        rows.append({"keyword": keyword.strip().lower(), "category": "human", "source_filter": "soft"})
    for keyword in STRICT_KEYWORDS:
        rows.append({"keyword": keyword.strip().lower(), "category": "strict_core", "source_filter": "strict"})

    df = pd.DataFrame(rows)
    df = df[df["keyword"].astype(str).str.len() > 0].copy()
    # keyword-meta zusammenziehen
    merged = (
        df.groupby("keyword", as_index=False)
        .agg(
            category=("category", lambda x: ",".join(sorted(set(x)))),
            source_filter=("source_filter", lambda x: ",".join(sorted(set(x)))),
        )
        .sort_values("keyword")
        .reset_index(drop=True)
    )
    return merged


def compile_pattern(keyword: str):
    # saubere wortgrenzen
    # auch bei extra spaces
    escaped = re.escape(keyword)
    escaped = escaped.replace(r"\ ", r"\s+")
    return re.compile(rf"\b{escaped}\b", flags=re.IGNORECASE)


def count_keyword_hits(text_series: pd.Series, keyword_table: pd.DataFrame):
    text_series = text_series.astype(str).fillna("")
    hit_counts = {}
    review_has_any = pd.Series(False, index=text_series.index)

    for row in keyword_table.itertuples(index=False):
        pattern = compile_pattern(row.keyword)
        hits = text_series.str.contains(pattern, na=False)
        hit_counts[row.keyword] = int(hits.sum())
        review_has_any = review_has_any | hits

    return hit_counts, review_has_any


def save_wordcloud_or_fallback(freq_map, title, output_png, top_n_bar=35):
    if not freq_map:
        return "none"

    if HAS_WORDCLOUD:
        try:
            wc = WordCloud(
                width=1600,
                height=900,
                background_color="white",
                max_words=250,
                collocations=False,
                font_path=detect_font_path(),
                prefer_horizontal=1.0,
            ).generate_from_frequencies(freq_map)
            fig = plt.figure(figsize=(16, 9))
            plt.imshow(wc, interpolation="bilinear")
            plt.axis("off")
            plt.title(title, fontsize=16)
            plt.tight_layout()
            fig.savefig(output_png, dpi=220)
            plt.close(fig)
            return "wordcloud"
        except Exception:
            pass

    top = sorted(freq_map.items(), key=lambda x: x[1], reverse=True)[:top_n_bar]
    if not top:
        return "none"
    terms = [w for w, _ in top][::-1]
    counts = [c for _, c in top][::-1]
    fig = plt.figure(figsize=(12, 9))
    plt.barh(terms, counts)
    plt.title(f"{title} (Fallback: Top AI Keywords)")
    plt.xlabel("Reviews with keyword")
    plt.tight_layout()
    fig.savefig(output_png, dpi=220)
    plt.close(fig)
    return "bar_fallback"


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "AI-fokussierte Wordcloud/Top-Keywords auf Basis der BA-Filterwoerter "
            "(soft + strict), getrennt nach positiv/negativ und Gruppen."
        )
    )
    parser.add_argument(
        "--min-doc-frequency",
        type=int,
        default=5,
        help="Mindestanzahl Reviews, in denen ein Keyword vorkommen muss.",
    )
    parser.add_argument(
        "--top-n",
        type=int,
        default=100,
        help="Top-N Keywords fuer CSV-Ausgabe.",
    )
    parser.add_argument(
        "--skip-group-splits",
        action="store_true",
        help="Nur overall ausgeben, keine gruppenspezifischen Outputs.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    ensure_directories()

    neg_df = load_negative_reviews()
    pos_df = load_positive_reviews()
    if neg_df.empty or pos_df.empty:
        raise RuntimeError("Positive/negative Reviews fehlen. Bitte zuerst die Datensammlung laufen lassen.")

    combined = pd.concat([neg_df, pos_df], ignore_index=True)
    combined = combined[combined["review_text"].astype(str).str.len() > 0].copy()

    keyword_table = build_keyword_table()

    scopes = [("overall", combined)]
    if not args.skip_group_splits:
        for group_name in sorted(combined["BA_Group"].dropna().unique()):
            scopes.append((group_name, combined[combined["BA_Group"] == group_name]))

    summary_rows = []
    category_rows = []

    for scope_name, scope_df in scopes:
        scope_slug = slugify(scope_name)
        for sentiment in ("negative", "positive"):
            subset = scope_df[scope_df["sentiment"] == sentiment].copy()
            n_reviews = len(subset)
            n_games = int(subset["appid"].nunique()) if "appid" in subset.columns else 0
            if n_reviews == 0:
                continue

            hit_counts, review_has_any = count_keyword_hits(subset["review_text"], keyword_table)
            n_reviews_with_ai_terms = int(review_has_any.sum())

            top_rows = []
            for row in keyword_table.itertuples(index=False):
                count = int(hit_counts.get(row.keyword, 0))
                if count < args.min_doc_frequency:
                    continue
                top_rows.append(
                    {
                        "scope": scope_name,
                        "sentiment": sentiment,
                        "keyword": row.keyword,
                        "category": row.category,
                        "source_filter": row.source_filter,
                        "review_count": count,
                        "review_share_pct": (count / n_reviews) * 100 if n_reviews else 0.0,
                    }
                )

            top_df = pd.DataFrame(top_rows).sort_values(
                by=["review_count", "keyword"], ascending=[False, True]
            )
            if len(top_df) > args.top_n:
                top_df = top_df.head(args.top_n).copy()

            top_csv = OUTPUT_DIR / f"ai_focus_top_terms_{scope_slug}_{sentiment}.csv"
            if top_df.empty:
                pd.DataFrame(
                    columns=[
                        "scope",
                        "sentiment",
                        "keyword",
                        "category",
                        "source_filter",
                        "review_count",
                        "review_share_pct",
                    ]
                ).to_csv(top_csv, index=False)
            else:
                top_df["review_share_pct"] = top_df["review_share_pct"].round(3)
                top_df.to_csv(top_csv, index=False)

            # category summary
            if not top_df.empty:
                exploded = top_df.assign(category=top_df["category"].str.split(",")).explode("category")
                cat_summary = (
                    exploded.groupby("category", as_index=False)["review_count"].sum().sort_values(
                        "review_count", ascending=False
                    )
                )
                for cat_row in cat_summary.itertuples(index=False):
                    category_rows.append(
                        {
                            "scope": scope_name,
                            "sentiment": sentiment,
                            "category": cat_row.category,
                            "review_count_sum": int(cat_row.review_count),
                        }
                    )

            freq_map = {r["keyword"]: int(r["review_count"]) for r in top_rows}
            out_img = OUTPUT_DIR / f"ai_focus_wordcloud_{scope_slug}_{sentiment}.png"
            viz = save_wordcloud_or_fallback(
                freq_map=freq_map,
                title=f"{scope_name} | {sentiment.title()} | AI-filter keywords",
                output_png=out_img,
            )

            summary_rows.append(
                {
                    "scope": scope_name,
                    "sentiment": sentiment,
                    "n_reviews": n_reviews,
                    "n_games": n_games,
                    "n_reviews_with_ai_terms": n_reviews_with_ai_terms,
                    "ai_term_review_share_pct": (n_reviews_with_ai_terms / n_reviews) * 100 if n_reviews else 0.0,
                    "n_keywords_nonzero": int(sum(1 for c in hit_counts.values() if c > 0)),
                    "n_keywords_after_min_freq": int(len(top_rows)),
                    "min_doc_frequency": int(args.min_doc_frequency),
                    "visualization": viz,
                    "top_terms_csv": str(top_csv),
                    "output_image": str(out_img),
                }
            )

    summary_df = pd.DataFrame(summary_rows).sort_values(["scope", "sentiment"]).reset_index(drop=True)
    if not summary_df.empty:
        summary_df["ai_term_review_share_pct"] = summary_df["ai_term_review_share_pct"].round(3)

    category_df = pd.DataFrame(category_rows).sort_values(
        ["scope", "sentiment", "review_count_sum"], ascending=[True, True, False]
    )

    summary_path = OUTPUT_DIR / "ai_focus_summary.csv"
    category_path = OUTPUT_DIR / "ai_focus_category_summary.csv"
    lexicon_path = OUTPUT_DIR / "ai_focus_lexicon.csv"

    summary_df.to_csv(summary_path, index=False)
    category_df.to_csv(category_path, index=False)
    keyword_table.to_csv(lexicon_path, index=False)

    print(f"FERTIG: {summary_path}")
    print(f"FERTIG: {category_path}")
    print(f"FERTIG: {lexicon_path}")


if __name__ == "__main__":
    main()
